git:
  git_version: 2.19.2
  git_prefix: /usr/local
  git_temp_dir: /tmp

git_install_from_source_dependencies:
  - gettext-devel
  - expat-devel
  - curl-devel
  - zlib-devel
  - perl-devel
  - openssl-devel
  - subversion-perl
  - make
  - gcc