
- name: update yum
  yum:
    name: "*"
    state: latest

- name: Ensure boto and boto3 modules are installed
  pip:
    name: ['boto3', 'botocore']

- name: Get Squid Root Certificate for tools from S3 bucket
  become: yes
  aws_s3:
    mode: get
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    bucket: "{{ bucketName }}"
    dest: /tmp/root_cert_squid_workspace.der
    object: /squid/root_cert_squid_workspace.der

- name: Install ca certificate tool
  yum:
    name: ca-certificates
    state: present

- name: Transfer the root certificate to trust store
  shell: mv /tmp/root_cert_squid_workspace.der /etc/pki/ca-trust/source/anchors/root_cert_squid_workspace.crt

- name: Enable the dynamic CA configuration feature
  shell: update-ca-trust force-enable

- name: Update CA trust
  shell: update-ca-trust extract

- name: Import a root certificate to Jenkin's java keystore (Jenkins uses Oracle JDK therefore separate task)
  java_cert:
    pkcs12_path: "/tmp/root_cert_squid_workspace.der"
    cert_alias: default
    keystore_path: /usr/bin/jdk1.8.0_211/jre/lib/security/cacerts
    keystore_pass: changeit
    keystore_create: yes
    state: present

- name: Import a root certificate to Jenkins java keystore - Jenkin uses Oracle JDK
  java_cert:
    pkcs12_path: "/tmp/root_cert_squid.der"
    cert_alias: default
    keystore_path: /usr/bin/jdk1.8.0_211/jre/lib/security/cacerts
    keystore_pass: "{{ sudo_pass }}"
    keystore_create: yes
    state: present
