- name: install pip via easy_install
  easy_install:
    name: pip
    state: latest

- name: Ensure boto and boto3 modules are installed
  pip:
    name: ['boto3', 'botocore']

- name: Get Squid Root Certificate for tools from S3 bucket
  become: yes
  aws_s3:
    mode: get
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    bucket: "{{ bucketName }}"
    dest: /tmp/root_cert_squid_tools.der
    object: /squid/root_cert_squid_tools.der

- name: Install ca certificate tool
  yum:
    name: ca-certificates
    state: present

- name: Transfer the root certificate to trust store
  shell: mv /tmp/root_cert_squid_tools.der /etc/pki/ca-trust/source/anchors/root_cert_squid_tools.der

- name: Enable the dynamic CA configuration feature
  shell: update-ca-trust force-enable

- name: Update CA trust
  shell: update-ca-trust extract

- name: Get Squid Root Certificate for tools from S3 bucket
  become: yes
  aws_s3:
    mode: get
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    bucket: "{{ bucketName }}"
    dest: /tmp/root_cert_squid.der
    object: /squid/root_cert_squid_tools.der

- name: Remove a root certificate if one already exists for JENKINS
  java_cert:
    executable: "/usr/java/jdk1.{{ jdk.version }}.0_{{ jdk.build }}-amd64/bin/keytool"
    cert_path: "/tmp/root_cert_squid.der"
    cert_alias: "squid"
    keystore_path: "/usr/java/jdk1.{{ jdk.version }}.0_{{ jdk.build }}-amd64/jre/lib/security/cacerts"
    keystore_pass: "changeit"
    state: absent
  when: "'jenkins' in inventory_hostname"

- name: Import a root certificate to java keystore for JENKINS
  java_cert:
    executable: "/usr/java/jdk1.{{ jdk.version }}.0_{{ jdk.build }}-amd64/bin/keytool"
    cert_path: "/tmp/root_cert_squid.der"
    cert_alias: "squid"
    keystore_path: "/usr/java/jdk1.{{ jdk.version }}.0_{{ jdk.build }}-amd64/jre/lib/security/cacerts"
    keystore_pass: "changeit"
    state: present
  when: "'jenkins' in inventory_hostname"

- name: Remove a root certificate if one already exists for JIRA
  java_cert:
    executable: "/opt/atlassian/jira/jre/bin/keytool"
    cert_path: "/tmp/root_cert_squid.der"
    cert_alias: "squid"
    keystore_path: "/opt/atlassian/jira/jre/lib/security/cacerts"
    keystore_pass: "changeit"
    state: absent
  when: "'jira' in inventory_hostname"

- name: Import a root certificate to java keystore for JIRA
  java_cert:
    executable: "/opt/atlassian/jira/jre/bin/keytool"
    cert_path: "/tmp/root_cert_squid.der"
    cert_alias: "squid"
    keystore_path: "/opt/atlassian/jira/jre/lib/security/cacerts"
    keystore_pass: "changeit"
    state: present
  when: "'jira' in inventory_hostname"

- name: Remove a root certificate if one already exists for BITBUCKET
  java_cert:
    executable: "/opt/atlassian/bitbucket/{{ bitbucket.version }}/jre/bin/keytool"
    cert_path: "/tmp/root_cert_squid.der"
    cert_alias: "squid"
    keystore_path: "/opt/atlassian/bitbucket/{{ bitbucket.version }}/jre/lib/security/cacerts"
    keystore_pass: "changeit"
    state: absent
  when: "'bitbucket' in inventory_hostname"

- name: Import a root certificate to java keystore for BITBUCKET
  java_cert:
    executable: "/opt/atlassian/bitbucket/{{ bitbucket.version }}/jre/bin/keytool"
    cert_path: "/tmp/root_cert_squid.der"
    cert_alias: "squid"
    keystore_path: "/opt/atlassian/bitbucket/{{ bitbucket.version }}/jre/lib/security/cacerts"
    keystore_pass: "changeit"
    state: present
  when: "'bitbucket' in inventory_hostname"

- name: Remove a root certificate if one already exists for CONFLUENCE
  java_cert:
    executable: "/opt/atlassian/confluence/jre/bin/keytool"
    cert_path: "/tmp/root_cert_squid.der"
    cert_alias: "squid"
    keystore_path: "/opt/atlassian/confluence/jre/lib/security/cacerts"
    keystore_pass: "changeit"
    state: absent
  when: "'confluence' in inventory_hostname"

- name: Import a root certificate to java keystore for CONFLUENCE
  java_cert:
    executable: "/opt/atlassian/confluence/jre/bin/keytool"
    cert_path: "/tmp/root_cert_squid.der"
    cert_alias: "squid"
    keystore_path: "/opt/atlassian/confluence/jre/lib/security/cacerts"
    keystore_pass: "changeit"
    state: present
  when: "'confluence' in inventory_hostname"