- name: Install SSM agent
  yum:
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    state: latest

- name: Install CloudWatch agent
  yum:
    name: https://s3.amazonaws.com/amazoncloudwatch-agent/centos/amd64/latest/amazon-cloudwatch-agent.rpm
    state: latest

- name: template setup script to hosts
  template:
    src: config.j2
    dest: /opt/aws/amazon-cloudwatch-agent/config.json
    owner: root

- name: Start CloudWatch agent with supplied configuration
  shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/config.json -s
