---
- name: Define git_install_from_source_dependencies.
  set_fact:
    git_install_from_source_dependencies: "{{ git.git_install_from_source_dependencies | list }}"
  when: git_install_from_source_dependencies is not defined

- name: Ensure git's dependencies are installed.
  package:
    name: "{{ git_install_from_source_dependencies }}"
    state: present

- name: Get installed version.
  command: >
    git --version
    warn=no
  changed_when: false
  failed_when: false
  check_mode: false
  register: git_installed_version
  
- name: Force git install if the version numbers do not match.
  set_fact:
    git_reinstall_from_source: true
  when:
    - (git_installed_version.rc == 0) and (git_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") is version(git.git_version, operator="!="))

- name: Get git binary
  unarchive:
    src: "https://www.kernel.org/pub/software/scm/git/git-{{ git.git_version }}.tar.gz"
    dest: "{{ git.git_temp_dir }}"
    remote_src: yes
  changed_when: false
  when: (git_installed_version.rc != 0) or git_reinstall_from_source

- name: Build git from source
  command: >
    make prefix={{ git.git_prefix }} {{ item }}
    chdir={{ git.git_temp_dir }}/git-{{ git.git_version }}
  with_items:
    - all
    - install
  when: (git_installed_version.rc != 0) or git_reinstall_from_source

- name: Remove git install file
  file:
    path: "{{ git.git_temp_dir }}/git-{{ git.git_version }}"
    state: absent
  changed_when: false
