- name: Install SSM and Cloudwatch Control and Augit agents
  hosts: squid-proxy-workspace
  gather_facts: true
  become: true
  serial: 1
  tasks:
    - import_role:
        name: ssm-cloudwatch

- name: Install Squid Proxy for workspaces
  hosts: squid-proxy-workspace
  gather_facts: true
  become: true
  tasks:
    - import_role:
        name: squid-proxy
